// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: filter.proto

package authz_filter_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthZProcessor_ProcessReq_FullMethodName = "/authzfilter.AuthZProcessor/processReq"
)

// AuthZProcessorClient is the client API for AuthZProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthZProcessorClient interface {
	ProcessReq(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterResponse, error)
}

type authZProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthZProcessorClient(cc grpc.ClientConnInterface) AuthZProcessorClient {
	return &authZProcessorClient{cc}
}

func (c *authZProcessorClient) ProcessReq(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilterResponse)
	err := c.cc.Invoke(ctx, AuthZProcessor_ProcessReq_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthZProcessorServer is the server API for AuthZProcessor service.
// All implementations must embed UnimplementedAuthZProcessorServer
// for forward compatibility.
type AuthZProcessorServer interface {
	ProcessReq(context.Context, *FilterRequest) (*FilterResponse, error)
	mustEmbedUnimplementedAuthZProcessorServer()
}

// UnimplementedAuthZProcessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthZProcessorServer struct{}

func (UnimplementedAuthZProcessorServer) ProcessReq(context.Context, *FilterRequest) (*FilterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessReq not implemented")
}
func (UnimplementedAuthZProcessorServer) mustEmbedUnimplementedAuthZProcessorServer() {}
func (UnimplementedAuthZProcessorServer) testEmbeddedByValue()                        {}

// UnsafeAuthZProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthZProcessorServer will
// result in compilation errors.
type UnsafeAuthZProcessorServer interface {
	mustEmbedUnimplementedAuthZProcessorServer()
}

func RegisterAuthZProcessorServer(s grpc.ServiceRegistrar, srv AuthZProcessorServer) {
	// If the following call pancis, it indicates UnimplementedAuthZProcessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthZProcessor_ServiceDesc, srv)
}

func _AuthZProcessor_ProcessReq_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthZProcessorServer).ProcessReq(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthZProcessor_ProcessReq_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthZProcessorServer).ProcessReq(ctx, req.(*FilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthZProcessor_ServiceDesc is the grpc.ServiceDesc for AuthZProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthZProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authzfilter.AuthZProcessor",
	HandlerType: (*AuthZProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "processReq",
			Handler:    _AuthZProcessor_ProcessReq_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "filter.proto",
}
